# Generated by Django 2.1.7 on 2019-03-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190315_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='text1',
        ),
        migrations.AlterField(
            model_name='blog',
            name='headline1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
