# Generated by Django 2.1.7 on 2019-03-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190318_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='target',
        ),
    ]
