# Generated by Django 2.1.7 on 2019-03-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190323_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='headline1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='headline2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='headline3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text3',
        ),
    ]
