# Generated by Django 2.1.7 on 2019-03-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190330_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='main_sentance',
        ),
    ]
