# Generated by Django 2.1.2 on 2019-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190330_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sex',
            field=models.CharField(blank=True, choices=[(1, '男性'), (2, '女性')], max_length=10, null=True, verbose_name='性別'),
        ),
    ]
