# Generated by Django 2.1.2 on 2019-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190413_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='age',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sex',
            field=models.CharField(choices=[(1, '男性'), (2, '女性')], default='男性', max_length=5, verbose_name='性別'),
        ),
    ]
