# Generated by Django 2.1.2 on 2019-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190413_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='男性', max_length=5, verbose_name='性別'),
        ),
    ]
