# Generated by Django 2.1.2 on 2019-04-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190413_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.PositiveSmallIntegerField(default=25, verbose_name='年齢')),
                ('sex', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='男性', max_length=5, verbose_name='性別')),
                ('text', models.TextField(verbose_name='内容')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('target_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Post', verbose_name='対象記事')),
            ],
        ),
    ]
