# Generated by Django 2.1.2 on 2019-04-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_recomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomment',
            name='target_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(default='まだ返信がありません。', verbose_name='返信内容'),
        ),
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
